### ISSUE TITLE
Missing scripts for preprocessing and training

### ISSUE THREAD

**Issue by owenzx** [i-machine-think/am-i-compositional#1]
Hi,

I've read your paper and I am interested in reproducing some of the results. But I noticed that you only released the scripts for testing. There is no "preprocess.py" or "train.py", which are both used in the bash file.

Is there any plan to release these scripts soon?

Thank you!

**Comment by dieuwkehupkes** [comment]
Hi!

The preprocess and train scripts are part of the openNMT and fairseq library. We will update the library more to be more clear about this! In the meantime, if you have more questions, feel free to reach out via email!

Best,

Dieuwke&Verna

**Comment by owenzx** [comment]
Thank you!

It solved my problems!
